### ISSUE TITLE
New object addition with immutable id fails inside existing array

### ISSUE THREAD

**Issue by utekau** [Kashoo/synctos#152] opened 2017-10-19 11:47 UTC
Hi,
There is a critical issue that we encountered today. We have an array with one object inside of it. Only id field of this object is immutable. On the other hand, if we want to add a new item to that array (with a new id of course) sync gw doesn't allow it. It expects us to have same id with the first element. We dig the code a bit but it looks complicated. If we would like to change an existing element that was ok but for addition of object fails.

**Comment by utekau** [comment] 2017-10-20 10:17
Hi again,

I might figure out what was going wrongly in the code. The issue is related with validateArray() function since in there, oldElementValue variable wasn't set as undefined/empty after the previous iteration. I did several test specifically for this problem and it seemed worked but I will wait your response and probably next release as well.

**Comment by OldSneerJaw** [comment] 2017-10-21 22:52
Nice work on identifying the cause of the problem, @utekau! FYI, I've created a new pull request (#153) that addresses the issue. It will hopefully be reviewed and merged by another of the project's collaborators/maintainers soon (but probably no earlier than Monday). I will publish a new release then.

**Comment by ziemek** [comment] 2017-10-23 19:44
Addressed by https://github.com/Kashoo/synctos/pull/153.

**Closed by ziemek** 2017-10-23 19:44 UTC
Labels: bug

**Comment by OldSneerJaw** [comment] 2017-10-23 22:49
@utekau: FYI, the newest version (1.9.3) includes a fix for the issue and has been published to npm.

**Comment by utekau** [comment] 2017-10-24 08:39
Thanks.
