### ISSUE TITLE
Deleting document with only replace authorized roles

### ISSUE THREAD

**Issue by utekau** [Kashoo/synctos#156] opened 2017-12-20 14:08 UTC
Hi,
I noticed that a document can be deleted by someone who has granted with replace role. For instance, in my sync gateway function, I have the following code.

```
...
authorizedRoles: {
   add: 'Manager'
}
```
Through on sync gateway rest api, I can delete that document with user whose role is Manager. However, unless I add remove/write capabilities, there shouldn't be any deletion occur. So, I check the code and I think in **getRequiredAuthorizations** function, you should append some extra deletion conditions, such as:

 `
} else if (!doc._deleted && !isDocumentMissingOrDeleted(oldDoc) && authorizationMap.replace) {`

Could you verify the bug and my solution and make a new release? I tested on my sync gateway and it worked but of course it was just a single case.

Thanks.

**Comment by dkichler** [comment] 2017-12-20 21:43
Hi Utku,

There seems to be some ambiguity in what you have reported.  You start with:
> a document can be deleted by someone who has granted with replace role

but your code snippet does not seem to support that, and does not reference a replace role.  

After some investigation of either case (i. user with add role only able to remove document, ii. user with replace role only able to remove document), I am unable to reproduce the conditions you describe.  

However, it does sound similar to issue  https://github.com/Kashoo/synctos/issues/149 that you previously reported.  This issue was addressed and published in https://github.com/Kashoo/synctos/releases/tag/v1.9.2. I would encourage you to double check what version of synctos you are using to generate sync functions.  

If issues persist after reviewing your dependencies and document definitions carefully, more detailed information about your document definition will be necessary to diagnose further.

**Comment by OldSneerJaw** [comment] 2017-12-20 23:26
On further inspection, it appears this bug report may indeed be valid. I will investigate further when I get a chance. In the meantime, @utekau, you should be able to work around the issue by including `replace` and `remove` privileges as empty arrays in the `authorizedRoles` configuration section to keep the authorization code from erroneously falling through to the next condition.

For example:

```
authorizedRoles: {
  add: 'Manager',
  replace: [],
  remove: []
}
```

**Comment by utekau** [comment] 2017-12-21 07:05
Hi guys,

Sorry, I just pasted wrong piece of my sync gateway code but as @OldSneerJaw said, the bug seems to be exist. Thank you for your support.

**Comment by ziemek** [comment] 2018-01-02 19:59
Addressed by https://github.com/Kashoo/synctos/pull/159.

**Closed by ziemek** 2018-01-02 19:59 UTC
Labels: bug
